#! /bin/sh
echo "$0: W: this is an old compat wrapper script for kvm-spice" >&2
echo "$0: W: please use qemu-system-x86_64 instead of $0" >&2

if echo "$@" | grep -q -E -e '(^|\s)-machine\s.*accel=' -e '(^|\s)-accel\s'; then
    # acceleration already set via commandline option - adding -enable-kvm would conflic"
    exec qemu-system-x86_64 "$@"
else
    exec qemu-system-x86_64 -enable-kvm "$@"
fi
